# Generated by Django 2.2.5 on 2020-11-06 09:59

from django.db import migrations, models
import vsurvey.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='surveyQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('intent', models.CharField(default='', max_length=100)),
                ('entity', models.CharField(default='', max_length=100)),
                ('audio', models.FileField(blank=True, default='myaudio.mp3', upload_to=vsurvey.models.question_idx_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='surveyUser',
            fields=[
                ('ph_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
