# Generated by Django 2.2.5 on 2020-11-06 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsurvey', '0003_remove_surveyquestion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
